Repository good-query/real-my-sql-study, pull requests merged in 2025-03, with the labels that each got.

#5 [임수빈] 3.1 사용자 식별 ~ 3.5 역할
  limsubinn/03. 사용자 및 권한/3.1 사용자 식별/README.md
  limsubinn/03. 사용자 및 권한/3.2 사용자 계정 관리/README.md
  limsubinn/03. 사용자 및 권한/3.3 비밀번호 관리/README.md
  limsubinn/03. 사용자 및 권한/3.4 권한(Privilege)/README.md
  limsubinn/03. 사용자 및 권한/3.5 역할(Role)/README.md
Labels: 내용 요약 ✨, 깊게 파보기 ⛏️

#1 [김대영] 3.1 사용자 식별 ~ 3.5 역할
  kdozlo/03_사용자 및 권한/3.1_사용자 식별.md
  kdozlo/03_사용자 및 권한/3.2_사용자 계정 관리.md
  kdozlo/03_사용자 및 권한/3.3_비밀번호 관리.md
  kdozlo/03_사용자 및 권한/3.4_권한.md
  kdozlo/03_사용자 및 권한/3.5_역할.md
Labels: 내용 요약 ✨, 깊게 파보기 ⛏️

#2 [전수민] 3.1 사용자 식별 ~ 3.5 역할
  soomin/Chapter 3 Role & Privilege/3.0) MySQL의 사용자 관리 전개도.md
  soomin/Chapter 3 Role & Privilege/3.1) 사용자 식별 .md
  soomin/Chapter 3 Role & Privilege/3.2) 사용자 계정 관리.md
  soomin/Chapter 3 Role & Privilege/3.3) 비밀번호 관리.md
  soomin/Chapter 3 Role & Privilege/3.4) 권한.md
  soomin/Chapter 3 Role & Privilege/3.5) 역할(Role).md
Labels: 내용 요약 ✨

#6 [정민호] 4.1 MySQL 엔진 아키텍처 ~ 4.2.2 외래 키 지원
  Geishaz/Chapter 4 Architecture/4.1) MySQL 엔진 아키텍쳐.md
  Geishaz/Chapter 4 Architecture/4.2) InnoDB 스토리지 엔진 아키텍처.md
  Geishaz/Chapter 4 Architecture/image-1.png
  Geishaz/Chapter 4 Architecture/image.png
Labels: SUMMARY ✨, DRILING ⛏️

#10 [김대영] 4.1 Mysql 엔진 아키텍처
  kdozlo/04_아키텍처/4.1_MySQL 엔진 아키텍처.md
Labels: SUMMARY ✨, DRILING ⛏️

#7 [임수빈] 4.1 MySQL 엔진 아키텍처 ~ 4.2.6 자동화된 장애 복구
  limsubinn/04. 아키텍처/4.1 MySQL 엔진 아키텍처/README.md
  limsubinn/04. 아키텍처/4.2 InnoDB 스토리지 엔진 아키텍처/README.md
Labels: SUMMARY ✨

#9 [전수민] 4.2.7 InnoDB 버퍼 풀 ~ 4.2.9 언두로그
  soomin/chapter-3-역할과-권한/3.0) MySQL의 사용자 관리 전개도.md
  soomin/chapter-3-역할과-권한/3.1) 사용자 식별 .md
  soomin/chapter-3-역할과-권한/3.2) 사용자 계정 관리.md
  soomin/chapter-3-역할과-권한/3.3) 비밀번호 관리.md
  soomin/chapter-3-역할과-권한/3.4) 권한.md
  soomin/chapter-3-역할과-권한/3.5) 역할(Role).md
  soomin/chapter-4-아키텍처/4.2.7 InnoDB 버퍼 풀/-목차-.md
  soomin/chapter-4-아키텍처/4.2.7 InnoDB 버퍼 풀/4.2.7.0_버퍼풀은_뭐하는_곳인가.md
  soomin/chapter-4-아키텍처/4.2.7 InnoDB 버퍼 풀/4.2.7.1_버퍼_풀의_크기_설정.md
  soomin/chapter-4-아키텍처/4.2.7 InnoDB 버퍼 풀/4.2.7.2_버퍼_풀의_구조.md
  soomin/chapter-4-아키텍처/4.2.7 InnoDB 버퍼 풀/4.2.7.3_버퍼_풀과_리두 로그.md
  soomin/chapter-4-아키텍처/4.2.7 InnoDB 버퍼 풀/4.2.7.4_버퍼 풀 플러시.md
  soomin/chapter-4-아키텍처/4.2.7 InnoDB 버퍼 풀/4.2.7.5_버퍼 풀 상태 백업 및 복구.md
  soomin/chapter-4-아키텍처/4.2.7 InnoDB 버퍼 풀/4.2.7.6_버퍼 풀의 적재 내용 확인.md
  soomin/chapter-4-아키텍처/4.2.8 Double Write Buffer.md
  soomin/chapter-4-아키텍처/4.2.9 언두로그.md
Labels: SUMMARY ✨, DRILING ⛏️
